# config.yaml
paths:
  path_auto: "data/auto-mpg.data"
  bikes_daily: "data/day.csv"
  bikes_hourly: "data/hour.csv"

preprocessing:
  scaling_method: "StandardScaler"       #standardize numerical features
  categorical_encoding: "OneHotEncoder"  #encode categorical variables

split:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42 #random state for reproducibility

rf_params:
  n_trees: [10, 50, 100]  # Number of trees
  max_depth: [5, 10, null] # Maximum depth of trees (null for None)
  min_samples_split: [2, 10]  # Minimum samples required to split a node
  max_features: [null, "sqrt", "log2"]  # Max features considered for splitting (null for None)'


metrics:
  regression_metrics:  # Metrics to evaluate regression models
    - "MSE"  # Mean Squared Error
    - "MAE"  # Mean Absolute Error
    - "R2"  # R-squared score

comparison:
  baseline_models:  # Models to compare custom Random Forest implementation with
    - "LinearRegression"
    - "SklearnRandomForest"
